[project]
name = "hello-world-with-layer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "orjson>=3.10.11",
    "requests>=2.32.3",
]

[dependency-groups]
dev = [
    "ipython>=8.29.0",
    "ruff>=0.7.3",
]
