[project]
name = "hello-world"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pandantic>=0.3.1",
]

[dependency-groups]
dev = [
    "ipython>=8.29.0",
]
